import { randomUUID } from "node:crypto";

const SENSITIVE_KEY =
  /authorization|cookie|password|passwd|secret|api[-_]?key|access[-_]?token|refresh[-_]?token|bearer/i;

export function argument(name, fallback = null, argv = process.argv) {
  const index = argv.indexOf(`--${name}`);
  const value = argv[index + 1];
  return index !== -1 && value && !value.startsWith("--") ? value : fallback;
}

export function hasFlag(name, argv = process.argv) {
  return argv.includes(`--${name}`);
}

export function normalizeBaseUrl(value = "https://www.currai.app") {
  return String(value).replace(/\/+$/, "");
}

export function redact(value, seen = new WeakSet()) {
  if (value == null || typeof value !== "object") return value;
  if (seen.has(value)) return "[Circular]";
  seen.add(value);
  if (Array.isArray(value)) return value.map((item) => redact(item, seen));
  return Object.fromEntries(
    Object.entries(value).map(([key, item]) => [
      key,
      SENSITIVE_KEY.test(key) ? "[REDACTED]" : redact(item, seen),
    ]),
  );
}

export function stringify(value) {
  try {
    return JSON.stringify(redact(value));
  } catch {
    return JSON.stringify({ value: String(value) });
  }
}

export async function postCapture({
  baseUrl,
  workspaceId,
  path,
  body,
  timeoutMs = 2_000,
  fetchImpl = fetch,
}) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetchImpl(`${normalizeBaseUrl(baseUrl)}${path}`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-currai-workspace-id": workspaceId,
      },
      body: JSON.stringify(redact(body)),
      signal: controller.signal,
    });
    let payload = null;
    try {
      payload = await response.json();
    } catch {
      payload = null;
    }
    return { ok: response.ok, status: response.status, body: payload };
  } catch (error) {
    return {
      ok: false,
      status: 0,
      body: null,
      error: error instanceof Error ? error.message : String(error),
    };
  } finally {
    clearTimeout(timeout);
  }
}

export async function captureSession(options, input = {}) {
  const sessionId = input.session_id ?? randomUUID();
  const response = await postCapture({
    ...options,
    path: "/api/v1/capture-session",
    body: {
      session_id: sessionId,
      user_data: {
        user_id: input.user_data?.user_id ?? "currai-skill-user",
        properties: input.user_data?.properties ?? {},
      },
      metadata: input.metadata ?? {},
      timestamp: input.timestamp,
      client_config: input.client_config ?? "currai-skill-native-http",
    },
  });
  return { ...response, sessionId };
}

export async function captureEvent(options, input) {
  const eventId = input.event_id ?? randomUUID();
  const response = await postCapture({
    ...options,
    path: "/api/v1/capture-event",
    body: {
      event_id: eventId,
      session_id: input.session_id,
      parent_id: input.parent_id ?? null,
      kind: input.kind ?? "event",
      primitive_name: input.primitive_name,
      args:
        typeof input.args === "string" ? input.args : stringify(input.args ?? {}),
      result:
        typeof input.result === "string"
          ? input.result
          : stringify(input.result ?? {}),
      success: input.success ?? true,
      latency: input.latency,
      timestamp: input.timestamp,
      metadata: redact(input.metadata ?? {}),
    },
  });
  return { ...response, eventId };
}

export function typescriptHelper() {
  return `// Generated by the Currai skill. Native HTTP only; no Currai SDK.
type CurraiEventKind =
  | "agent"
  | "model"
  | "tool"
  | "mcp_tool"
  | "retriever"
  | "guardrail"
  | "evaluator"
  | "event";

type CurraiEvent = {
  eventId?: string;
  sessionId: string;
  parentId?: string | null;
  kind: CurraiEventKind;
  name: string;
  args?: unknown;
  result?: unknown;
  success?: boolean;
  latency?: number;
  timestamp?: number;
  metadata?: Record<string, unknown>;
};

const sensitiveKey =
  /authorization|cookie|password|passwd|secret|api[-_]?key|access[-_]?token|refresh[-_]?token|bearer/i;

function redact(value: unknown, seen = new WeakSet<object>()): unknown {
  if (value == null || typeof value !== "object") return value;
  if (seen.has(value)) return "[Circular]";
  seen.add(value);
  if (Array.isArray(value)) return value.map((item) => redact(item, seen));
  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>).map(([key, item]) => [
      key,
      sensitiveKey.test(key) ? "[REDACTED]" : redact(item, seen),
    ]),
  );
}

function encode(value: unknown): string {
  try {
    return JSON.stringify(redact(value));
  } catch {
    return JSON.stringify({ value: String(value) });
  }
}

async function send(path: string, body: unknown): Promise<boolean> {
  const baseUrl = process.env.CURRAI_BASE_URL;
  const workspaceId = process.env.CURRAI_WORKSPACE_ID;
  if (!baseUrl || !workspaceId) return false;
  try {
    const response = await fetch(\`\${baseUrl.replace(/\\\/$/, "")}\${path}\`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-currai-workspace-id": workspaceId,
      },
      body: JSON.stringify(redact(body)),
      signal: AbortSignal.timeout(2_000),
    });
    return response.ok;
  } catch {
    return false;
  }
}

export async function captureCurraiSession(input: {
  sessionId: string;
  userId: string;
  properties?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  timestamp?: number;
}): Promise<boolean> {
  return send("/api/v1/capture-session", {
    session_id: input.sessionId,
    user_data: { user_id: input.userId, properties: input.properties ?? {} },
    metadata: input.metadata ?? {},
    timestamp: input.timestamp,
    client_config: "currai-skill-native-http",
  });
}

export async function captureCurraiEvent(
  input: CurraiEvent,
): Promise<boolean> {
  return send("/api/v1/capture-event", {
    event_id: input.eventId ?? crypto.randomUUID(),
    session_id: input.sessionId,
    parent_id: input.parentId ?? null,
    kind: input.kind,
    primitive_name: input.name,
    args: encode(input.args ?? {}),
    result: encode(input.result ?? {}),
    success: input.success ?? true,
    latency: input.latency,
    timestamp: input.timestamp,
    metadata: redact(input.metadata ?? {}),
  });
}
`;
}

export function javascriptHelper() {
  return `// Generated by the Currai skill. Native HTTP only; no Currai SDK.
const sensitiveKey =
  /authorization|cookie|password|passwd|secret|api[-_]?key|access[-_]?token|refresh[-_]?token|bearer/i;

function redact(value, seen = new WeakSet()) {
  if (value == null || typeof value !== "object") return value;
  if (seen.has(value)) return "[Circular]";
  seen.add(value);
  if (Array.isArray(value)) return value.map((item) => redact(item, seen));
  return Object.fromEntries(
    Object.entries(value).map(([key, item]) => [
      key,
      sensitiveKey.test(key) ? "[REDACTED]" : redact(item, seen),
    ]),
  );
}

function encode(value) {
  try {
    return JSON.stringify(redact(value));
  } catch {
    return JSON.stringify({ value: String(value) });
  }
}

async function send(path, body) {
  const baseUrl = process.env.CURRAI_BASE_URL;
  const workspaceId = process.env.CURRAI_WORKSPACE_ID;
  if (!baseUrl || !workspaceId) return false;
  try {
    const response = await fetch(\`\${baseUrl.replace(/\\\/$/, "")}\${path}\`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-currai-workspace-id": workspaceId,
      },
      body: JSON.stringify(redact(body)),
      signal: AbortSignal.timeout(2_000),
    });
    return response.ok;
  } catch {
    return false;
  }
}

export async function captureCurraiSession(input) {
  return send("/api/v1/capture-session", {
    session_id: input.sessionId,
    user_data: { user_id: input.userId, properties: input.properties ?? {} },
    metadata: input.metadata ?? {},
    timestamp: input.timestamp,
    client_config: "currai-skill-native-http",
  });
}

export async function captureCurraiEvent(input) {
  return send("/api/v1/capture-event", {
    event_id: input.eventId ?? crypto.randomUUID(),
    session_id: input.sessionId,
    parent_id: input.parentId ?? null,
    kind: input.kind,
    primitive_name: input.name,
    args: encode(input.args ?? {}),
    result: encode(input.result ?? {}),
    success: input.success ?? true,
    latency: input.latency,
    timestamp: input.timestamp,
    metadata: redact(input.metadata ?? {}),
  });
}
`;
}

export function pythonHelper() {
  return `# Generated by the Currai skill. Native HTTP only; no Currai SDK.
from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
import uuid
from typing import Any

_SENSITIVE = re.compile(
    r"authorization|cookie|password|passwd|secret|api[-_]?key|access[-_]?token|refresh[-_]?token|bearer",
    re.IGNORECASE,
)


def _redact(value: Any) -> Any:
    if isinstance(value, dict):
        return {
            key: "[REDACTED]" if _SENSITIVE.search(str(key)) else _redact(item)
            for key, item in value.items()
        }
    if isinstance(value, (list, tuple)):
        return [_redact(item) for item in value]
    return value


def _encode(value: Any) -> str:
    try:
        return json.dumps(_redact(value), default=str)
    except Exception:
        return json.dumps({"value": str(value)})


def _send(path: str, body: dict[str, Any]) -> bool:
    base_url = os.getenv("CURRAI_BASE_URL", "").rstrip("/")
    workspace_id = os.getenv("CURRAI_WORKSPACE_ID", "")
    if not base_url or not workspace_id:
        return False
    request = urllib.request.Request(
        f"{base_url}{path}",
        data=json.dumps(_redact(body)).encode("utf-8"),
        headers={
            "content-type": "application/json",
            "x-currai-workspace-id": workspace_id,
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=2) as response:
            return 200 <= response.status < 300
    except (urllib.error.URLError, TimeoutError, ValueError):
        return False


def capture_currai_session(
    session_id: str,
    user_id: str,
    *,
    properties: dict[str, Any] | None = None,
    metadata: dict[str, Any] | None = None,
    timestamp: int | None = None,
) -> bool:
    return _send(
        "/api/v1/capture-session",
        {
            "session_id": session_id,
            "user_data": {"user_id": user_id, "properties": properties or {}},
            "metadata": metadata or {},
            "timestamp": timestamp,
            "client_config": "currai-skill-native-http",
        },
    )


def capture_currai_event(
    *,
    session_id: str,
    kind: str,
    name: str,
    args: Any = None,
    result: Any = None,
    event_id: str | None = None,
    parent_id: str | None = None,
    success: bool = True,
    latency: float | None = None,
    timestamp: int | None = None,
    metadata: dict[str, Any] | None = None,
) -> bool:
    return _send(
        "/api/v1/capture-event",
        {
            "event_id": event_id or str(uuid.uuid4()),
            "session_id": session_id,
            "parent_id": parent_id,
            "kind": kind,
            "primitive_name": name,
            "args": _encode(args or {}),
            "result": _encode(result or {}),
            "success": success,
            "latency": latency,
            "timestamp": timestamp,
            "metadata": _redact(metadata or {}),
        },
    )
`;
}
