#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import {
  argument,
  hasFlag,
  javascriptHelper,
  normalizeBaseUrl,
  pythonHelper,
  typescriptHelper,
} from "./lib/currai.mjs";

const dir = argument("dir", process.cwd());
const workspaceId = argument("workspace-id", process.env.CURRAI_WORKSPACE_ID);
const mode = argument("mode", "local");
const envMode = argument("env-mode", "file");
const baseUrl = normalizeBaseUrl(
  argument("base-url", process.env.CURRAI_BASE_URL ?? "https://www.currai.app"),
);
const json = hasFlag("json");

try {
  if (!workspaceId) throw new Error("--workspace-id is required");
  if (!existsSync(dir)) throw new Error(`target directory does not exist: ${dir}`);
  if (!new Set(["local", "prod"]).has(mode)) {
    throw new Error("--mode must be local or prod");
  }
  if (!new Set(["file", "manual"]).has(envMode)) {
    throw new Error("--env-mode must be file or manual");
  }

  const detection = detect(dir);
  if (!detection.ok) throw new Error(detection.error);
  const filesChanged = [];
  const warnings = [];
  const helper = helperTarget(dir, detection);
  const helperContent =
    detection.language === "python"
      ? pythonHelper()
      : detection.language === "javascript"
        ? javascriptHelper()
        : typescriptHelper();

  writeGenerated(helper, helperContent, filesChanged);

  const env = {
    CURRAI_WORKSPACE_ID: workspaceId,
    CURRAI_BASE_URL: baseUrl,
  };
  if (envMode === "file") {
    const envPath = environmentTarget(dir, detection.runtime, mode);
    writeEnvironment(dir, envPath, env, filesChanged, warnings);
  } else {
    warnings.push("manual env mode; configure CURRAI_WORKSPACE_ID and CURRAI_BASE_URL in the server runtime");
  }

  if (detection.entrypoints.length === 0) {
    warnings.push("no AI entrypoint candidate was detected; locate the real model, agent, or tool call before wiring capture");
  } else {
    warnings.push(
      `wire ${relative(dir, helper)} into the confirmed AI entrypoint; candidates: ${detection.entrypoints.join(", ")}`,
    );
  }

  print({
    ok: true,
    framework: detection.framework,
    language: detection.language,
    runtime: detection.runtime,
    workspaceId,
    baseUrl,
    helper: relative(dir, helper),
    entrypoints: detection.entrypoints,
    reference: referenceFor(detection.framework),
    appIntegrationReady: false,
    filesChanged,
    env,
    warnings,
  });
} catch (error) {
  print({ ok: false, error: error instanceof Error ? error.message : String(error) });
  process.exitCode = 1;
}

function detect(target) {
  const scriptDir = dirname(fileURLToPath(import.meta.url));
  const result = spawnSync(
    process.execPath,
    [join(scriptDir, "detect.mjs"), "--dir", target, "--json"],
    { encoding: "utf8" },
  );
  const output = result.stdout.trim();
  if (!output) {
    return { ok: false, error: result.stderr.trim() || "application detection failed" };
  }
  try {
    return JSON.parse(output);
  } catch {
    return { ok: false, error: output };
  }
}

function helperTarget(target, detection) {
  if (detection.language === "python") {
    return join(target, existsSync(join(target, "src")) ? "src" : "", "currai.py");
  }
  const extension = detection.language === "javascript" ? "mjs" : "ts";
  if (detection.runtime === "nextjs") return join(target, "lib", `currai.${extension}`);
  return join(target, existsSync(join(target, "src")) ? "src" : "", `currai.${extension}`);
}

function environmentTarget(target, runtime, selectedMode) {
  if (selectedMode === "prod") return join(target, ".env.production");
  if (runtime === "nextjs") return join(target, ".env.local");
  return join(target, ".env");
}

function writeGenerated(path, content, changed) {
  const existing = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (existing !== null && !existing.startsWith("// Generated by the Currai skill") && !existing.startsWith("# Generated by the Currai skill")) {
    throw new Error(`refusing to overwrite existing non-Currai helper: ${path}`);
  }
  if (existing === content) return;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  changed.push(path);
}

function writeEnvironment(target, path, values, changed, warnings) {
  const known = findExistingEnvironmentValues(target);
  const existing = existsSync(path) ? readFileSync(path, "utf8") : "";
  const lines = existing ? existing.split(/\r?\n/) : [];
  const next = [...lines];
  let didChange = false;
  for (const [key, value] of Object.entries(values)) {
    const present = known.get(key);
    if (present) {
      if (present.value !== value) {
        warnings.push(`${key} already exists in ${present.file}; its value was preserved`);
      }
      continue;
    }
    next.push(`${key}=${value}`);
    didChange = true;
  }
  if (!didChange) return;
  const content = `${next.filter((line, index, all) => line !== "" || index < all.length - 1).join("\n")}\n`;
  writeFileSync(path, content);
  changed.push(path);
}

function findExistingEnvironmentValues(target) {
  const found = new Map();
  for (const file of [".env", ".env.local", ".env.production", ".env.development"]) {
    const path = join(target, file);
    if (!existsSync(path)) continue;
    for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
      const match = line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/);
      if (match && !found.has(match[1])) {
        found.set(match[1], { file, value: match[2] });
      }
    }
  }
  return found;
}

function referenceFor(framework) {
  if (framework === "vercel-ai") return "references/frameworks.md#nextjs-and-vercel-ai-sdk";
  if (framework === "openai-ts" || framework === "anthropic-ts") {
    return "references/frameworks.md#openai-and-anthropic-typescript";
  }
  if (framework === "langchain-ts" || framework === "mastra-ts") {
    return "references/frameworks.md#langchain-and-mastra-typescript";
  }
  if (framework === "mcp-ts") return "references/frameworks.md#typescript-mcp-servers";
  if (framework === "mcp-py") return "references/frameworks.md#python-mcp-servers";
  if (framework.endsWith("-py") || framework === "python") {
    return "references/frameworks.md#python-model-and-agent-applications";
  }
  return "references/frameworks.md#common-contract";
}

function print(value) {
  if (json) {
    console.log(JSON.stringify(value));
    return;
  }
  if (!value.ok) {
    console.error(`error: ${value.error}`);
    return;
  }
  console.log(`framework: ${value.framework}`);
  console.log(`helper:    ${value.helper}`);
  for (const file of value.filesChanged) console.log(`changed:   ${relative(dir, file)}`);
  for (const warning of value.warnings) console.log(`warning:   ${warning}`);
}
